### ISSUE TITLE
Automate versioning and releases

### ISSUE THREAD

**Issue by GitRon** [django-crispy-forms/crispy-tailwind#149]
Previous ticket: #147 

---

@justinmayer He's a separate ticket so we don't mess around too much in the other one (which is unrelated to the actual task)

**Comment by GitRon** [comment]
Question: Would it make sense to migrate to [flit](https://pypi.org/project/flit/)? I heard it's a newer and better way for package releasing and though I use it in my packages and it works great, I have no real clue about alternatives.

**Comment by justinmayer** [comment]
These days there are a number of tools related to packaging, often with varying scopes and target use cases. While I have never used Flit, I have experience with other build back-ends such as [PDM](https://github.com/pdm-project/pdm) and [Hatch/Hatchling](https://github.com/pypa/hatch). When it comes to the build process itself, I get the impression that all of these build back-ends perform sufficiently well when used with the Python [`build`](https://github.com/pypa/build) package as the build front-end.

I usually reach for tools like PDM / Hatch because they provide more features such as virtual environment handling and dependency management. Moreover, I prefer how they store the canonical version number in `pyproject.toml` instead of Flit's location inside `packagename/__init__.py`.

There are many articles out there that talk about how these projects differ from one another. One of the more comprehensive articles concluded that "PDM is really close to the ideal", which aligns with my own assessment as well: https://chriswarrick.com/blog/2023/01/15/how-to-improve-python-packaging/#summary

**Comment by GitRon** [comment]
Awesome, happy to learn why "your" solution is better than flit 🙂
