### ISSUE TITLE
In ModelChoiceField 'selected'-Tag is missing, when ModelForm is invalid

### ISSUE THREAD

**Issue by datenrebell** [django-crispy-forms/crispy-tailwind#98]
Hello,

I have a model with at least two ForeignKey-ModelFields. Both fields are blank = False. I Use a Modelform and Crispy-Tailwind. If the Foreign-Fields in an object are assigned except one and you commit the form, the form will be invalid. The problem is, that in the next rendering of all ForeignFields the "selected"-HTML-tag are missing and so all Foreign-Fields are unselected. The problem does not occur without Crispy-Tailwind. 

You can see the problem in my repository: https://github.com/datenrebell/bug_in_crispy_tailwind

I hope you can help me with this Issue.
Thanks.

**Comment by tissieres** [comment]
I have the same problem. It is related to #90 since the default django `django/forms/widgets/select.html` template is badly overriden by this package. I fixed this by applying the @tailwindcss/forms plugin and overriding the `field.html` template of this application to remove the inclusion of the custom `select.html`.
